name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: get_results
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json --json-file-output=snyk.json
      - name: Upload results artifact
        uses: actions/upload-artifact@v2
        with: 
           name: results
           path: ./snyk.json
